SystemOrganization addCategory: #'Ring2-Core'!
SystemOrganization addCategory: 'Ring2-Core-Announcements'!
SystemOrganization addCategory: 'Ring2-Core-Announcements-Classes'!
SystemOrganization addCategory: 'Ring2-Core-Announcements-Methods'!
SystemOrganization addCategory: 'Ring2-Core-Announcements-Packages'!
SystemOrganization addCategory: 'Ring2-Core-Environment'!
SystemOrganization addCategory: 'Ring2-Core-Kernel'!
SystemOrganization addCategory: 'Ring2-Core-Parsing'!
